### ISSUE TITLE
Android 5.1 instant crash

### ISSUE THREAD

**Issue by jussirantala** [nitaliano/react-native-mapbox-gl#1059]
Crashes when trying to show mapbox map on Android 5.1 using latest react-native-mapbox-gl
```
I/ReactNativeJS( 2535): TabView render, selected tab: Map (index: 2)

I/ReactNativeJS( 2535): MapContainer render

W/EGL_emulation( 2535): eglSurfaceAttrib not implemented

W/OpenGLRenderer( 2535): Failed to set EGL_SWAP_BEHAVIOR on surface 0xe181dbc0, error=EGL_SUCCESS

V/WindowManager(  519): Adding window Window{224587eb u0 SurfaceView} at 6 of 11 (before Window{2807bc32 u0 com.mycompany.myapp/com.mycompany.myapp.MainActivity})

D/        ( 2535): HostConnection::get() New Host Connection established 0xdbbcea90, tid 2612

E/AndroidRuntime( 2535): FATAL EXCEPTION: GLThread 274

E/AndroidRuntime( 2535): Process: com.mycompany.myapp, PID: 2535

E/AndroidRuntime( 2535): com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigException: eglChooseConfig() failed

E/AndroidRuntime( 2535): 	at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getNumberOfConfigurations(EGLConfigChooser.java:85)

E/AndroidRuntime( 2535): 	at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:62)

E/AndroidRuntime( 2535): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1023)

E/AndroidRuntime( 2535): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1400)

E/AndroidRuntime( 2535): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
W/ActivityManager(  519):   Force finishing activity 1 com.mycompany.myapp/.MainActivity

D/        (  519): HostConnection::get() New Host Connection established 0xdfb77cc0, tid 1408
```

**Comment by nitaliano** [comment]
Android emulator, genymotion, or physical device and what type?

**Comment by jussirantala** [comment]
Genymotion. On a physical device (Galaxy Note 5) the map is black

**Comment by nitaliano** [comment]
try adding `textureMode` as a prop on your map and test it out on a physical device

**Comment by kristfal** [comment]
This is a rather old issue. In an effort to clean up stale issues, I'll close this. 

Please update to latest master branch and reopen if the problem persists.
