### ISSUE TITLE
Crash on launch on Android

### ISSUE THREAD

**Issue by AntoineChwat** [nitaliano/react-native-mapbox-gl#1184]
When I try to start the example application on Android available [here](https://www.mapbox.com/help/first-steps-react-native-sdk/), the app crashes with the following stack trace:

```
05-02 12:00:50.236 3853-3853/com.mapboxtest E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.mapboxtest, PID: 3853
                                                              java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.mapbox.mapboxsdk.net.ConnectivityReceiver@1fdb5aad
                                                                  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:876)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                               Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.mapbox.mapboxsdk.Mapbox.connected' on a null object reference
                                                                  at com.mapbox.mapboxsdk.Mapbox.isConnected(Mapbox.java:138)
                                                                  at com.mapbox.mapboxsdk.net.ConnectivityReceiver.isConnected(ConnectivityReceiver.java:120)
                                                                  at com.mapbox.mapboxsdk.net.ConnectivityReceiver.onReceive(ConnectivityReceiver.java:86)
                                                                  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

I installed the project just like it is recommended on github using npm, and it works like a charm on iOS.

**Comment by crockpotveggies** [comment]
@AntoineChwat can you please post what resolved your problem? Looks like you closed this but I'm having the same issue.

**Comment by AntoineChwat** [comment]
@crockpotveggies Hum this was a while ago so I'm really not sure but it might be because I did not register the API key in my js code since I was using my own tiles but that caused a crash on Android so I had to input my API key anyway and then it worked. Hope that's it!
