### ISSUE TITLE
Android app crashing after setAccessToken

### ISSUE THREAD

**Issue by dcharp05** [nitaliano/react-native-mapbox-gl#1195]
Hello,
I installed the library following the steps and could only get the app to run on Android after downgrading to 6.0.0. When I try to upgrade to 6.03 or the latest version. The app crashes after calling setAccessToken. Im testing on an Pixel 2 Xl and there are no logs or anything else to debug from.

**Comment by nitaliano** [comment]
What is your logcat saying? I'm running the latest version fine on a Pixel and Pixel 2

**Comment by dcharp05** [comment]
Thats the last thing that prints before setAccessToken is called. It is also crashing on my nexus 5x, but is running on IOS simulator. 
<img width="1844" alt="mapbox" src="https://user-images.githubusercontent.com/14933353/39972334-94cbb3a6-56d2-11e8-9550-7a419c68e0ef.png">

**Comment by dcharp05** [comment]
@nitaliano Do you have any suggestions?

**Comment by darkredz** [comment]
I have the same issue here when testing with latest mapbox with RN 0.56 on android 8.0
executing react-native run-android to test on phone will crash when setAccessToken is called

**Comment by darkredz** [comment]
07-12 00:38:30.505  1126  9525 W WindowManager: Exception thrown when updateSurfaceStatusWindowStateAnimator{2edaaff com.testapp/com.testapp.MainActivity}: android.os.DeadObjectException

**Comment by ste00martin** [comment]
I have the same issue too

**Comment by alexxsanchezm** [comment]
This is the output when I i get when I call `MapboxGL.setAccessToken(conf['mapboxAccessToken']);` of course method is not defined, I know it because I checked in inside the source code.
 
        MapboxTelemetry  V  Initializing telemetry.
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.yovoytaxi.passengerapp, PID: 21756
                         E  java.lang.NoSuchMethodError: No static method toHumanReadableAscii(Ljava/lang/String;)Ljava/lang/String; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okh
                            ttp3.internal.Util' appears in /data/app/com.yovoytaxi.passengerapp-WxUpnZIgAkg9XhgzmiKWiQ==/base.apk)
                         E      at com.mapbox.services.android.telemetry.MapboxTelemetry.setUserAgent(MapboxTelemetry.java:315)
                         E      at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:174)
                         E      at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:125)
                         E      at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
                         E      at com.mapbox.rctmgl.modules.RCTMGLModule$1.run(RCTMGLModule.java:279)
                         E      at android.os.Handler.handleCallback(Handler.java:790)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                         E      at android.os.Looper.loop(Looper.java:164)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6494)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                 zygote  E  Failed sending reply to debugger: Broken pipe

**Comment by ddolheguy** [comment]
I can confirm I also get the same issue on ReactNative 0.56 when using Android 8

**Comment by JILeXanDR** [comment]
The same problem on device `Mi A1 - 8.0.0`

**Comment by kristfal** [comment]
The fix may most likely be found here:

https://github.com/mapbox/react-native-mapbox-gl/issues/1139#issuecomment-379647942

@nitaliano This issue should go away when we upgrade the native android mapbox library.

**Comment by JILeXanDR** [comment]
@kristfal It helped!
