### ISSUE TITLE
The project example CustomIcon.js was broken

### ISSUE THREAD

**Issue by hersonrodrigues** [nitaliano/react-native-mapbox-gl#1260]
The example on react-native-mapbox-gl/example/src/components/CustomIcon.js was broken

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.reactnativeprovinggrounds, PID: 1886
                  java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } bqHint=1 (has extras) } in com.mapbox.mapboxsdk.net.ConnectivityReceiver@63f5479
                      at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1195)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                   Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.mapbox.mapboxsdk.Mapbox.connected' on a null object reference
                      at com.mapbox.mapboxsdk.Mapbox.isConnected(Mapbox.java:138)
                      at com.mapbox.mapboxsdk.net.ConnectivityReceiver.isConnected(ConnectivityReceiver.java:120)
                      at com.mapbox.mapboxsdk.net.ConnectivityReceiver.onReceive(ConnectivityReceiver.java:86)
                      at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
                      at android.os.Handler.handleCallback(Handler.java:751) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6776) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
```

**Comment by nitaliano** [comment]
you're not in the example app though your bundle id is` com.reactnativeprovinggrounds` are you sure you setup gradle correctly and that you set your access token? The example works for me.

**Comment by hersonrodrigues** [comment]
I create another bundle ID, but works fine, I think the problem is about the start connect with token or something like that, after put the MapboxGL.setAccessToken(MY_TOKEN) before to export the component, it's works.

**Comment by nitaliano** [comment]
you should be setting your access token under your imports not inside of the components to avoid a race condition, glad it's working closing out
