### ISSUE TITLE
UnsupportedOperationException: eglCreateWindowSurface() can only be called with an instance of Surface, SurfaceView, SurfaceHolder or SurfaceTexture at the moment.

### ISSUE THREAD

**Issue by Gp2mv3** [nitaliano/react-native-mapbox-gl#1284]
Some of our users on Android are triggering this error. It seems to come from the Java SDK. Here is the stacktrace:
```
java.lang.UnsupportedOperationException: eglCreateWindowSurface() can only be called with an instance of Surface, SurfaceView, SurfaceHolder or SurfaceTexture at the moment.
    at com.google.android.gles_jni.EGLImpl.eglCreateWindowSurface(EGLImpl.java:97)
    at com.mapbox.mapboxsdk.maps.renderer.textureview.TextureViewRenderThread$EGLHolder.createSurface(TextureViewRenderThread.java:382)
    at com.mapbox.mapboxsdk.maps.renderer.textureview.TextureViewRenderThread.run(TextureViewRenderThread.java:248)
```
It's triggered at map's first rendering. It seems to be a race condition between, no ?

**Comment by L-Yeiser** [comment]
We just saw this crash for the first time. Have been unable to reproduce it.

**Comment by haideralishah** [comment]
I am also facing this issue? any update
and I can't reproduce it.
