### ISSUE TITLE
App keeps stopping on android

### ISSUE THREAD

**Issue by Marcsimm** [nitaliano/react-native-mapbox-gl#1302]
I have followed the installation instructions for android and ios and ios. The map works fine on ios but on Android as soon as I use it in a component the app just crashes

info 
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26

logcat error 

```
07-23 10:36:24.637 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager
07-23 10:36:24.650 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager$MapShadowNode
07-23 10:36:24.652 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.mapview.RCTMGLAndroidTextureMapViewManager
07-23 10:36:24.653 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.light.RCTMGLLightManager
07-23 10:36:24.654 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotationManager
07-23 10:36:24.659 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.annotation.RCTMGLCalloutManager
07-23 10:36:24.660 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.sources.RCTMGLVectorSourceManager
07-23 10:36:24.661 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.sources.RCTMGLShapeSourceManager
07-23 10:36:24.663 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.sources.RCTMGLRasterSourceManager
07-23 10:36:24.664 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.sources.RCTMGLImageSourceManager
07-23 10:36:24.665 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.layers.RCTMGLFillLayerManager
07-23 10:36:24.666 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.layers.RCTMGLFillExtrusionLayerManager
07-23 10:36:24.669 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.layers.RCTMGLLineLayerManager
07-23 10:36:24.671 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.layers.RCTMGLCircleLayerManager
07-23 10:36:24.673 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.layers.RCTMGLSymbolLayerManager
07-23 10:36:24.675 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.layers.RCTMGLRasterLayerManager
07-23 10:36:24.679 5430-5451/com.driverapplication W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mapbox.rctmgl.components.styles.layers.RCTMGLBackgroundLayerManager
07-23 10:36:25.126 5430-5430/com.driverapplication I/iverapplicatio: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.services.android.telemetry.location.GoogleLocationEngine>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/GoogleApiClient$ConnectionCallbacks;
        at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
        at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
        at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
        at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
        at void com.mapbox.rctmgl.modules.RCTMGLModule$1.run() (RCTMGLModule.java:279)
        at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
        at void com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(android.os.Message) (MessageQueueThreadHandler.java:29)
        at void android.os.Looper.loop() (Looper.java:193)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6642)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.driverapplication-ZEDiSWxS3h19URIoZBZl4w==/base.apk"],nativeLibraryDirectories=[/data/app/com.driverapplication-ZEDiSWxS3h19URIoZBZl4w==/lib/x86, /data/app/com.driverapplication-ZEDiSWxS3h19URIoZBZl4w==/base.apk!/lib/x86, /system/lib]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:126)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
        at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
        at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
        at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
        at void com.mapbox.rctmgl.modules.RCTMGLModule$1.run() (RCTMGLModule.java:279)
        at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
        at void com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(android.os.Message) (MessageQueueThreadHandler.java:29)
        at void android.os.Looper.loop() (Looper.java:193)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6642)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
    Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.services.android.telemetry.location.GoogleLocationEngine>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/GoogleApiClient$ConnectionCallbacks;
        at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
        at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
        at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
        at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
        at void com.mapbox.rctmgl.modules.RCTMGLModule$1.run() (RCTMGLModule.java:279)
        at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
        at void com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(android.os.Message) (MessageQueueThreadHandler.java:29)
        at void android.os.Looper.loop() (Looper.java:193)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6642)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.driverapplication-ZEDiSWxS3h19URIoZBZl4w==/base.apk"],nativeLibraryDirectories=[/data/app/com.driverapplication-ZEDiSWxS3h19URIoZBZl4w==/lib/x86, /data/app/com.driverapplication-ZEDiSWxS3h19URIoZBZl4w==/base.apk!/lib/x86, /system/lib]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:126)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
        at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
        at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
        at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
        at void com.mapbox.rctmgl.modules.RCTMGLModule$1.run() (RCTMGLModule.java:279)
        at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
        at void com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(android.os.Message) (MessageQueueThreadHandler.java:29)
        at void android.os.Looper.loop() (Looper.java:193)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6642)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
07-23 10:36:25.132 5430-5430/com.driverapplication V/MapboxTelemetry: Initializing telemetry.
07-23 10:36:25.139 5430-5430/com.driverapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.driverapplication, PID: 5430
    java.lang.NoSuchMethodError: No static method toHumanReadableAscii(Ljava/lang/String;)Ljava/lang/String; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/com.driverapplication-ZEDiSWxS3h19URIoZBZl4w==/base.apk)
        at com.mapbox.services.android.telemetry.MapboxTelemetry.setUserAgent(MapboxTelemetry.java:315)
        at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:174)
        at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:125)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
        at com.mapbox.rctmgl.modules.RCTMGLModule$1.run(RCTMGLModule.java:279)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by CptFabulouso** [comment]
For the last error `java.lang.NoSuchMethodError: No static method toHumanReadableAscii` take a look [at this solution](https://github.com/mapbox/react-native-mapbox-gl/issues/1139#issuecomment-379647942). Not sure if it fixes the rest

**Comment by Marcsimm** [comment]
@CptFabulouso That solved it thanks!
