### ISSUE TITLE
 [Android] Error: 'Warning: Failed propType: undefined is not a function...

### ISSUE THREAD

**Issue by lwhiteley** [nitaliano/react-native-mapbox-gl#136]
Getting this error when i use the android example

``` shell
 'Warning: Failed propType: undefined is not a function (evaluating \'typeChecker(\npropValue,\ni,\ncomponentName,\nlocation,\npropFullName + \'[\' + i + \']\')\') Check the render method of `ReactMapViewWrapper`.'

```

in my project im using react-native:0.14.+ 
not sure if your are currently supporting this version

It kills the app after start up

other logs:

```
D/dalvikvm( 4993): GC_CONCURRENT freed 399K, 5% free 12305K/12871K, paused 15ms+3ms, total 56ms
D/dalvikvm( 4993): Trying to load lib /data/data/com.app/lib/libmapbox-gl.so 0xa6d74100
D/dalvikvm( 4993): Added shared lib /data/data/com.app/lib/libmapbox-gl.so 0xa6d74100
I/mbgl    ( 4993): {Map}[Android]: Not activating as we are not ready
E/libEGL  ( 4993): call to OpenGL ES API with no current context (logged once per thread)
I/mbgl    ( 4993): {Map}[Android]: Not deactivating as we are not ready
I/mbgl    ( 4993): {Main}[OpenGL]: EGL Vendor: Android
I/mbgl    ( 4993): {Main}[OpenGL]: EGL Version: 1.4 Android META-EGL
I/mbgl    ( 4993): {Main}[OpenGL]: EGL Client APIs: OpenGL_ES
I/mbgl    ( 4993): {Main}[OpenGL]: EGL Client Extensions: EGL_KHR_image_base EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer 
E/mbgl    ( 4993): {Main}[OpenGL]: eglChooseConfig() returned no configs.
F/libc    ( 4993): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128), thread 4993

...

W/SocketClient(  120): write error (Broken pipe)
I/BootReceiver( 3040): Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)
D/dalvikvm( 3040): GC_FOR_ALLOC freed 26K, 17% free 13786K/16519K, paused 21ms, total 21ms
W/InputDispatcher( 3040): channel '537ff50c com.app/com.app.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 3040): channel '537ff50c com.app/com.app.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
D/Zygote  ( 3018): Process 4993 terminated by signal (11)
W/InputDispatcher( 3040): Attempted to unregister already unregistered input channel '537ff50c com.app/com.app.MainActivity (server)'
I/WindowManager( 3040): WINDOW DIED Window{537ff50c com.app/com.app.MainActivity paused=false}
I/ActivityManager( 3040): Process com.app (pid 4993) has died.
W/ActivityManager( 3040): Force removing ActivityRecord{53785188 com.app/.MainActivity}: app died, no saved state
W/WindowManager( 3040): Failed looking up window
W/WindowManager( 3040): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@537cbcb0 does not exist
W/WindowManager( 3040):     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7640)
W/WindowManager( 3040):     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7631)
W/WindowManager( 3040):     at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:854)
W/WindowManager( 3040):     at android.os.BinderProxy.sendDeathNotice(Binder.java:449)
W/WindowManager( 3040):     at dalvik.system.NativeStart.run(Native Method)
I/WindowState( 3040): WIN DEATH: null
W/EGL_genymotion( 3198): eglSurfaceAttrib not implemented
W/InputMethodManagerService( 3040): Got RemoteException sending setActive(false) notification to pid 4993 uid 10050
```

**Comment by lwhiteley** [comment]
i managed to get rid of the first error by changing

``` js
coordinates: React.PropTypes.arrayOf(),
```

to 

``` js
coordinates: React.PropTypes.array,
```

app still dying though

**Comment by lwhiteley** [comment]
made a breakthrough, it was partially the device, i did manage to upgrade the code to support react-native 0.14.+ though

**Comment by bsudekum** [comment]
@lwhiteley what did you do to upgrade? I'm seeing some errors myself.

**Comment by lwhiteley** [comment]
im sending a pull request. see PR #137

cleaning it up a bit, you can review
