### ISSUE TITLE
Null object reference: Attempt to invoke virtual method '

### ISSUE THREAD

**Issue by deepmehtait** [nitaliano/react-native-mapbox-gl#1379]
Not able to view map after on Android. Followed [install guide](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/install.md) and when tried to run the code followed few [comments](https://github.com/mapbox/react-native-mapbox-gl/issues/1341#issuecomment-415322430) from other issues. Still not able to view the map on android.

RN Version: 0.54.2
Android OS: 9
@mapbox/react-native-mapbox-gl: ^6.1.2

```javascript
.... Other imports
import Mapbox from '@mapbox/react-native-mapbox-gl';
....

class sampleName extends PureComponent {

...
componentWillMount() {
 Mapbox.setAccessToken('Token');
  }
...

render() {
    <View
        style={[s.flx1]}
    >
        <Mapbox.MapView
            styleURL={Mapbox.StyleURL.Street}
            zoomLevel={15}
            centerCoordinate={[11.256, 43.770]}
            style={[s.flx1]}
        />
    }
}
```
```java
2018-10-02 15:16:43.604 31361-31361/com.kamino.wdt E/MapView: Exception in MapView.OnMapChangedListener
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxsdk.camera.CameraPosition com.mapbox.mapboxsdk.maps.MapboxMap.getCameraPosition()' on a null object reference
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.makeRegionPayload(RCTMGLMapView.java:1260)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.onMapChanged(RCTMGLMapView.java:695)
        at com.mapbox.mapboxsdk.maps.MapView.onMapChange(MapView.java:572)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:862)
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitialize(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.<init>(NativeMapView.java:84)
        at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:308)
        at com.mapbox.mapboxsdk.maps.MapView.access$1000(MapView.java:68)
        at com.mapbox.mapboxsdk.maps.MapView$MapViewLayoutListener.onGlobalLayout(MapView.java:894)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.init(RCTMGLMapView.java:1071)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.onAfterUpdateTransaction(RCTMGLMapViewManager.java:69)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.onAfterUpdateTransaction(RCTMGLMapViewManager.java:37)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:35)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:233)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:816)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:929)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:989)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-10-02 15:16:43.606 31361-31361/com.kamino.wdt E/MapView: Exception in MapView.OnMapChangedListener
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxsdk.camera.CameraPosition com.mapbox.mapboxsdk.maps.MapboxMap.getCameraPosition()' on a null object reference
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.makeRegionPayload(RCTMGLMapView.java:1260)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.onMapChanged(RCTMGLMapView.java:695)
        at com.mapbox.mapboxsdk.maps.MapView.onMapChange(MapView.java:572)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:862)
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeResizeView(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.resizeView(NativeMapView.java:144)
        at com.mapbox.mapboxsdk.maps.MapView.onSizeChanged(MapView.java:535)
        at android.view.View.sizeChange(View.java:20848)
        at android.view.View.setFrame(View.java:20809)
        at android.view.View.layout(View.java:20669)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:205)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:190)
        at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:128)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:822)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:929)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:989)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by kristfal** [comment]
Please retry with master branch. If the problem still persists, try using the example app as a baseline for your repo setup.
