### ISSUE TITLE
Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE

### ISSUE THREAD

**Issue by crockpotveggies** [nitaliano/react-native-mapbox-gl#1387]
Installed this plugin and created a component exactly like the minimal example from the docs here: https://www.mapbox.com/help/first-steps-react-native-sdk/

The app will crash immediately with the error: 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.superham, PID: 14349
    java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.mapbox.mapboxsdk.net.ConnectivityReceiver@5c20f80
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_51267(LoadedApk.java:1305)
        at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(Unknown Source:4)
        at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(Unknown Source:0)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.mapbox.mapboxsdk.Mapbox.connected' on a null object reference
        at com.mapbox.mapboxsdk.Mapbox.isConnected(Mapbox.java:138)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.isConnected(ConnectivityReceiver.java:120)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.onReceive(ConnectivityReceiver.java:86)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_51267(LoadedApk.java:1295)
```

My guess is that there is an issue during packaging, but after double-checking the instructions for Android setup I'm unsure how to resolve it.

Full logs for this are available here: https://gist.github.com/crockpotveggies/13e4d6bfbd6b65156925e69755d4415d

**Comment by GrosJob** [comment]
+1

**Comment by timxyz** [comment]
Did you follow the part about adding `MapboxGL.setAccessToken(Config.MAPBOX_TOKEN);`?

I had the same crash without that line (the docs held in the repo don't seem to mention adding it).

**Comment by kristfal** [comment]
Pleas retry with master and make sure you you set up the required permissions in the Android manifest.

**Comment by armendu** [comment]
Just putting this out there in case some one needs it. In cases when this message is showing, add the required permission and add this line as well:
`MapboxGL.setConnected(true);`
