### ISSUE TITLE
@mapbox/react-native-mapbox-gl 6.1.3 run  to react native  0.57.5 crash on android

### ISSUE THREAD

**Issue by giantss** [nitaliano/react-native-mapbox-gl#1428]
@mapbox/react-native-mapbox-gl 6.1.3 run  to react native  0.57.5 crash on android，run normally on ios。

Below is the crash log:

```
  --------- beginning of crash
11-19 16:41:28.345 23651-23651/com.mapboxtest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapboxtest, PID: 23651
    java.lang.NoSuchMethodError: No static method toHumanReadableAscii(Ljava/lang/String;)Ljava/lang/String; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/com.mapboxtest-1/base.apk)
        at com.mapbox.services.android.telemetry.MapboxTelemetry.setUserAgent(MapboxTelemetry.java:315)
        at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:174)
        at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:125)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
        at com.mapbox.rctmgl.modules.RCTMGLModule$1.run(RCTMGLModule.java:279)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6236)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by kristfal** [comment]
See https://github.com/mapbox/react-native-mapbox-gl/issues/1139#issuecomment-379647942 for workaround

**Comment by giantss** [comment]
@kristfal  https://github.com/mapbox/react-native-mapbox-gl/issues/1139#issuecomment-439827307 Is this naming method internally or accidentally written wrong?
