### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by haf** [nitaliano/react-native-mapbox-gl#1445]
```
Installing build/Build/Products/Debug-iphonesimulator/RNMapboxGLExample.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNMapboxGLExample.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

```

for iOS.

```
success Saved lockfile.
$ node ./scripts/set_access_token.js
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'accesstoken'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/Users/h/dev/haf/react-native-mapbox-gl/example/scripts/set_access_token.js:4:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
error Command failed with exit code 1.
```

For `yarn install`

**Comment by kristfal** [comment]
You need to add the file `accesstoken` to the root folder of the example with your mapbox access token before doing `yarn install`. 

More info about this in the readme.
