### ISSUE TITLE
Cannot resolve module 'react-native-mapbox-gl'

### ISSUE THREAD

**Issue by BenjaminConant** [nitaliano/react-native-mapbox-gl#202]
Hi All, 

Just tried a fresh install following the instructions here https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md. The app builds fine but as soon as I require `react-native-mapbox-gl` I get 

```
ERROR in ./src/containers/Home.js
Module not found: Error: Cannot resolve module 'react-native-mapbox-gl' in /Users/benconant/Dev/eastern-passenger/src/containers
 @ ./src/containers/Home.js 17:27-60
```

I am not really sure where to go :( Here is my package.json.

```
{
  "name": "App",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android-setup-port": "adb reverse tcp:8081 tcp:8080",
    "bundle": "rnws bundle",
    "test": "eslint src",
    "start": "rnws start"
  },
  "dependencies": {
    "react-native": "0.16",
    "react-native-button": "^1.3.1",
    "react-native-side-menu": "^0.15.5"
  },
  "devDependencies": {
    "babel-core": "^6.1.2",
    "babel-eslint": "^4.1.3",
    "babel-loader": "^6.0.0",
    "babel-preset-es2015": "^6.0.14",
    "babel-preset-react": "^6.0.14",
    "babel-preset-stage-1": "^6.1.2",
    "eslint": "^1.8.0",
    "eslint-loader": "^1.1.1",
    "eslint-plugin-react": "^3.6.3",
    "react": "^0.14.3",
    "react-native-side-menu": "^0.15.5",
    "react-native-webpack-server": "^0.8.2",
    "react-redux": "3.1",
    "redux": "^3.0.4",
    "redux-multi": "^0.1.10",
    "redux-thunk": "^1.0.0",
    "validator": "^4.4.0",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.1"
  },
  "license": "MIT"
}
```

I have noticed that `react-native-mapbox-gl` is not in my dependencies even though I ran with `--save` ... when running  `npm install react-native-mapbox-gl --save` I got this error which seems unrelated ...

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-mapbox-gl" "--save"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native@0.16.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-side-menu@0.15.5 wants react-native@>= 0.9.0
npm ERR! peerinvalid Peer react-native-webpack-server@0.8.2 wants react-native@>=0.13.0 <0.16 || 0.15.0-rc

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benconant/Dev/eastern-passenger/npm-debug.log
```

`react-native-mapbox-gl` IS in my `node_modules` folder so I am not sure why it can't be resolved. This is the packadge.json for the `react-native-mapbox-gl` in my node_modules folder

```
{
  "name": "react-native-mapbox-gl",
  "description": "A Mapbox GL react native module for creating custom maps",
  "version": "2.2.0",
  "author": {
    "name": "Bobby Sudekum"
  },
  "keywords": [
    "gl",
    "ios",
    "android",
    "mapbox",
    "react-component",
    "react-native"
  ],
  "licenses": [
    {
      "type": "BSD",
      "url": "https://github.com/mapbox/react-native-mapbox-gl/blob/master/LICENSE.md"
    }
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/mapbox/react-native-mapbox-gl.git"
  },
  "scripts": {
    "preinstall": "./scripts/download-mapbox-gl-native-ios.sh 3.0.0",
    "test": "eslint example.js index.ios.js index.android.js",
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "devDependencies": {
    "babel-eslint": "^3.1.20",
    "eslint": "^0.24.0",
    "eslint-plugin-react": "^2.6.4"
  },
  "gitHead": "9fd4c140f99d8eede35aeada4d212419f9c64263",
  "bugs": {
    "url": "https://github.com/mapbox/react-native-mapbox-gl/issues"
  },
  "homepage": "https://github.com/mapbox/react-native-mapbox-gl#readme",
  "_id": "react-native-mapbox-gl@2.2.0",
  "_shasum": "9a61bac750356ec445e7f3df6d82312e12627692",
  "_from": "react-native-mapbox-gl@*",
  "_npmVersion": "2.14.7",
  "_nodeVersion": "4.2.3",
  "_npmUser": {
    "name": "bsudekum",
    "email": "bobby@mapbox.com"
  },
  "maintainers": [
    {
      "name": "bsudekum",
      "email": "bobby@mapbox.com"
    },
    {
      "name": "brentvatne",
      "email": "brentvatne@gmail.com"
    }
  ],
  "dist": {
    "shasum": "9a61bac750356ec445e7f3df6d82312e12627692",
    "tarball": "http://registry.npmjs.org/react-native-mapbox-gl/-/react-native-mapbox-gl-2.2.0.tgz"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/react-native-mapbox-gl/-/react-native-mapbox-gl-2.2.0.tgz",
  "readme": "ERROR: No README data found!"
}
```

**Comment by BenjaminConant** [comment]
npm debug log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'react-native-mapbox-gl',
1 verbose cli   '--save' ]
2 info using npm@2.14.4
3 info using node@v4.0.0
4 verbose install initial load of /Users/benconant/Dev/eastern-passenger/package.json
5 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/babel-core/package.json
6 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/babel-eslint/package.json
7 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/babel-loader/package.json
8 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/babel-preset-es2015/package.json
9 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/babel-preset-react/package.json
10 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/babel-preset-stage-1/package.json
11 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/eslint/package.json
12 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/eslint-loader/package.json
13 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/eslint-plugin-react/package.json
14 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/react/package.json
15 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/react-native/package.json
16 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/react-native-button/package.json
17 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl/package.json
18 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/react-native-side-menu/package.json
19 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/react-native-webpack-server/package.json
20 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/react-redux/package.json
21 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/redux/package.json
22 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/redux-multi/package.json
23 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/redux-thunk/package.json
24 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/validator/package.json
25 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/webpack/package.json
26 verbose installManyTop reading scoped package data from /Users/benconant/Dev/eastern-passenger/node_modules/webpack-dev-server/package.json
27 info package.json react-native-mapbox-gl@2.2.0 No license field.
28 verbose readDependencies loading dependencies from /Users/benconant/Dev/eastern-passenger/package.json
29 verbose install react-native-mapbox-gl is installed as 2.2.0
30 silly cache add args [ 'react-native-mapbox-gl', null ]
31 verbose cache add spec react-native-mapbox-gl
32 silly cache add parsed spec Result {
32 silly cache add   raw: 'react-native-mapbox-gl',
32 silly cache add   scope: null,
32 silly cache add   name: 'react-native-mapbox-gl',
32 silly cache add   rawSpec: '',
32 silly cache add   spec: '*',
32 silly cache add   type: 'range' }
33 silly addNamed react-native-mapbox-gl@*
34 verbose addNamed "*" is a valid semver range for react-native-mapbox-gl
35 silly addNameRange { name: 'react-native-mapbox-gl', range: '*', hasData: false }
36 silly mapToRegistry name react-native-mapbox-gl
37 silly mapToRegistry using default registry
38 silly mapToRegistry registry https://registry.npmjs.org/
39 silly mapToRegistry uri https://registry.npmjs.org/react-native-mapbox-gl
40 verbose addNameRange registry:https://registry.npmjs.org/react-native-mapbox-gl not in flight; fetching
41 verbose request uri https://registry.npmjs.org/react-native-mapbox-gl
42 verbose request no auth needed
43 info attempt registry request try #1 at 6:20:48 PM
44 verbose request id 6beebe93691d68d1
45 verbose etag "22N3RI99XMUJWSR10TEEK7HKN"
46 http request GET https://registry.npmjs.org/react-native-mapbox-gl
47 http 304 https://registry.npmjs.org/react-native-mapbox-gl
48 silly get cb [ 304,
48 silly get   { date: 'Sun, 20 Dec 2015 23:20:48 GMT',
48 silly get     via: '1.1 varnish',
48 silly get     'cache-control': 'max-age=300',
48 silly get     etag: '"22N3RI99XMUJWSR10TEEK7HKN"',
48 silly get     age: '0',
48 silly get     connection: 'keep-alive',
48 silly get     'x-served-by': 'cache-iad2124-IAD',
48 silly get     'x-cache': 'MISS',
48 silly get     'x-cache-hits': '0',
48 silly get     'x-timer': 'S1450653648.640194,VS0,VE68',
48 silly get     vary: 'Accept' } ]
49 verbose etag https://registry.npmjs.org/react-native-mapbox-gl from cache
50 verbose get saving react-native-mapbox-gl to /Users/benconant/.npm/registry.npmjs.org/react-native-mapbox-gl/.cache.json
51 silly addNameRange number 2 { name: 'react-native-mapbox-gl', range: '*', hasData: true }
52 silly addNameRange versions [ 'react-native-mapbox-gl',
52 silly addNameRange   [ '0.0.1',
52 silly addNameRange     '0.0.2',
52 silly addNameRange     '0.0.4',
52 silly addNameRange     '0.0.5',
52 silly addNameRange     '0.0.6',
52 silly addNameRange     '0.0.7',
52 silly addNameRange     '0.0.9',
52 silly addNameRange     '0.1.1',
52 silly addNameRange     '0.1.2',
52 silly addNameRange     '0.1.3',
52 silly addNameRange     '0.1.4',
52 silly addNameRange     '0.1.5',
52 silly addNameRange     '0.2.1',
52 silly addNameRange     '0.3.0',
52 silly addNameRange     '0.4.0',
52 silly addNameRange     '0.4.1',
52 silly addNameRange     '0.4.2',
52 silly addNameRange     '1.0.0',
52 silly addNameRange     '1.1.0',
52 silly addNameRange     '2.0.0',
52 silly addNameRange     '2.1.0',
52 silly addNameRange     '2.1.1',
52 silly addNameRange     '2.1.2',
52 silly addNameRange     '2.1.3',
52 silly addNameRange     '2.1.4',
52 silly addNameRange     '2.2.0' ] ]
53 silly addNamed react-native-mapbox-gl@2.2.0
54 verbose addNamed "2.2.0" is a plain semver version for react-native-mapbox-gl
55 silly cache afterAdd react-native-mapbox-gl@2.2.0
56 verbose afterAdd /Users/benconant/.npm/react-native-mapbox-gl/2.2.0/package/package.json not in flight; writing
57 verbose afterAdd /Users/benconant/.npm/react-native-mapbox-gl/2.2.0/package/package.json written
58 silly install resolved [ { name: 'react-native-mapbox-gl',
58 silly install resolved     description: 'A Mapbox GL react native module for creating custom maps',
58 silly install resolved     version: '2.2.0',
58 silly install resolved     author: { name: 'Bobby Sudekum' },
58 silly install resolved     keywords:
58 silly install resolved      [ 'gl',
58 silly install resolved        'ios',
58 silly install resolved        'android',
58 silly install resolved        'mapbox',
58 silly install resolved        'react-component',
58 silly install resolved        'react-native' ],
58 silly install resolved     licenses: [ [Object] ],
58 silly install resolved     repository:
58 silly install resolved      { type: 'git',
58 silly install resolved        url: 'git+https://github.com/mapbox/react-native-mapbox-gl.git' },
58 silly install resolved     scripts:
58 silly install resolved      { preinstall: './scripts/download-mapbox-gl-native-ios.sh 3.0.0',
58 silly install resolved        test: 'eslint example.js index.ios.js index.android.js',
58 silly install resolved        start: 'node_modules/react-native/packager/packager.sh' },
58 silly install resolved     devDependencies:
58 silly install resolved      { 'babel-eslint': '^3.1.20',
58 silly install resolved        eslint: '^0.24.0',
58 silly install resolved        'eslint-plugin-react': '^2.6.4' },
58 silly install resolved     gitHead: '9fd4c140f99d8eede35aeada4d212419f9c64263',
58 silly install resolved     bugs: { url: 'https://github.com/mapbox/react-native-mapbox-gl/issues' },
58 silly install resolved     homepage: 'https://github.com/mapbox/react-native-mapbox-gl#readme',
58 silly install resolved     _id: 'react-native-mapbox-gl@2.2.0',
58 silly install resolved     _shasum: '9a61bac750356ec445e7f3df6d82312e12627692',
58 silly install resolved     _from: 'react-native-mapbox-gl@*',
58 silly install resolved     _npmVersion: '2.14.7',
58 silly install resolved     _nodeVersion: '4.2.3',
58 silly install resolved     _npmUser: { name: 'bsudekum', email: 'bobby@mapbox.com' },
58 silly install resolved     maintainers: [ [Object], [Object] ],
58 silly install resolved     dist:
58 silly install resolved      { shasum: '9a61bac750356ec445e7f3df6d82312e12627692',
58 silly install resolved        tarball: 'http://registry.npmjs.org/react-native-mapbox-gl/-/react-native-mapbox-gl-2.2.0.tgz' },
58 silly install resolved     directories: {},
58 silly install resolved     _resolved: 'https://registry.npmjs.org/react-native-mapbox-gl/-/react-native-mapbox-gl-2.2.0.tgz',
58 silly install resolved     readme: 'ERROR: No README data found!' } ]
59 info install react-native-mapbox-gl@2.2.0 into /Users/benconant/Dev/eastern-passenger
60 info installOne react-native-mapbox-gl@2.2.0
61 verbose installOne of react-native-mapbox-gl to /Users/benconant/Dev/eastern-passenger not in flight; installing
62 verbose lock using /Users/benconant/.npm/_locks/react-native-mapbox-gl-4da3c6524120f9fa.lock for /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl
63 silly install write writing react-native-mapbox-gl 2.2.0 to /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl
64 verbose unbuild node_modules/react-native-mapbox-gl
65 info preuninstall react-native-mapbox-gl@2.2.0
66 info uninstall react-native-mapbox-gl@2.2.0
67 verbose unbuild rmStuff react-native-mapbox-gl@2.2.0 from /Users/benconant/Dev/eastern-passenger/node_modules
68 info postuninstall react-native-mapbox-gl@2.2.0
69 silly gentlyRm /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl is being purged from base /Users/benconant/Dev/eastern-passenger
70 verbose gentlyRm don't care about contents; nuking /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl
71 silly vacuum-fs purging /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl
72 silly vacuum-fs quitting because other entries in /Users/benconant/Dev/eastern-passenger/node_modules
73 verbose tar unpack /Users/benconant/.npm/react-native-mapbox-gl/2.2.0/package.tgz
74 verbose tar unpacking to /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl
75 silly gentlyRm /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl is being purged
76 verbose gentlyRm don't care about contents; nuking /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl
77 silly gunzTarPerm modes [ '755', '644' ]
78 silly gunzTarPerm extractEntry package.json
79 silly gunzTarPerm extractEntry .npmignore
80 silly gunzTarPerm extractEntry index.android.js
81 silly gunzTarPerm extractEntry index.ios.js
82 silly gunzTarPerm extractEntry android/example.js
83 silly gunzTarPerm extractEntry android/API.md
84 silly gunzTarPerm extractEntry android/build.gradle
85 silly gunzTarPerm extractEntry android/install.md
86 silly gunzTarPerm extractEntry android/src/main/AndroidManifest.xml
87 silly gunzTarPerm extractEntry android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLManager.java
88 silly gunzTarPerm extractEntry android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLPackage.java
89 silly gunzTarPerm extractEntry .eslintrc
90 silly gunzTarPerm extractEntry CHANGELOG.md
91 silly gunzTarPerm extractEntry ios/example.js
92 silly gunzTarPerm extractEntry ios/API.md
93 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLStyle.h
94 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLAnnotationImage.h
95 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLMapCamera.h
96 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLMultiPoint.h
97 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLOverlay.h
98 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLPointAnnotation.h
99 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLPolygon.h
100 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLPolyline.h
101 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLShape.h
102 silly gunzTarPerm extractEntry ios/RCTMapboxGL/MGLGeometry.h
103 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/README
104 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/default_marker.png
105 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/Compass@3x.png
106 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/Compass.png
107 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/api_mapbox_com-digicert.der
108 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/api_mapbox_com-geotrust.der
109 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/Compass@2x.png
110 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/default_marker@2x.png
111 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/default_marker@3x.png
112 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/mapbox.png
113 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/mapbox@2x.png
114 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/mapbox@3x.png
115 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.bundle/star_tilestream_net.der
116 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Mapbox.h
117 silly gunzTarPerm extractEntry ios/RCTMapboxGL/RCTMapboxGL.h
118 silly gunzTarPerm extractEntry ios/RCTMapboxGL/RCTMapboxGL.m
119 silly gunzTarPerm extractEntry ios/RCTMapboxGL/RCTMapboxGLManager.h
120 silly gunzTarPerm extractEntry ios/RCTMapboxGL/RCTMapboxGLManager.m
121 silly gunzTarPerm extractEntry ios/RCTMapboxGL/Settings.bundle/Root.plist
122 silly gunzTarPerm extractEntry ios/RCTMapboxGL/libMapbox.a
123 silly gunzTarPerm extractEntry ios/RCTMapboxGL.podspec
124 silly gunzTarPerm extractEntry ios/RCTMapboxGL.xcodeproj/project.pbxproj
125 silly gunzTarPerm extractEntry ios/RCTMapboxGLTests/Info.plist
126 silly gunzTarPerm extractEntry ios/install.md
127 silly gunzTarPerm extractEntry LICENSE.md
128 silly gunzTarPerm extractEntry readme.md
129 silly gunzTarPerm extractEntry scripts/download-mapbox-gl-native-ios.sh
130 verbose write writing to /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl/package.json
131 info preinstall react-native-mapbox-gl@2.2.0
132 verbose unsafe-perm in lifecycle false
133 verbose readDependencies loading dependencies from /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl/package.json
134 verbose readDependencies loading dependencies from /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl/package.json
135 silly install resolved []
136 verbose about to build /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl
137 info build /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl
138 info linkStuff react-native-mapbox-gl@2.2.0
139 silly linkStuff react-native-mapbox-gl@2.2.0 has /Users/benconant/Dev/eastern-passenger/node_modules as its parent node_modules
140 verbose linkBins react-native-mapbox-gl@2.2.0
141 verbose linkMans react-native-mapbox-gl@2.2.0
142 verbose rebuildBundles react-native-mapbox-gl@2.2.0
143 info install react-native-mapbox-gl@2.2.0
144 info postinstall react-native-mapbox-gl@2.2.0
145 verbose unlock done using /Users/benconant/.npm/_locks/react-native-mapbox-gl-4da3c6524120f9fa.lock for /Users/benconant/Dev/eastern-passenger/node_modules/react-native-mapbox-gl
146 verbose validateInstall loading /Users/benconant/Dev/eastern-passenger/package.json for validation
147 verbose stack Error: The package react-native@0.16.0 does not satisfy its siblings' peerDependencies requirements!
147 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:125:32
147 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:268:7
147 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
147 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
147 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
147 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
147 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
147 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
147 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
147 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
148 verbose cwd /Users/benconant/Dev/eastern-passenger
149 error Darwin 15.0.0
150 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-mapbox-gl" "--save"
151 error node v4.0.0
152 error npm  v2.14.4
153 error code EPEERINVALID
154 error peerinvalid The package react-native@0.16.0 does not satisfy its siblings' peerDependencies requirements!
154 error peerinvalid Peer react-native-side-menu@0.15.5 wants react-native@>= 0.9.0
154 error peerinvalid Peer react-native-webpack-server@0.8.2 wants react-native@>=0.13.0 <0.16 || 0.15.0-rc
155 verbose exit [ 1, true ]
```

**Comment by terimyaki** [comment]
It seems this problem due to react-native-webpack-server, not mapbox-gl. Its package.json is not allowing react-native to be over 0.16. But it seems from this recent commit that if you change it to 0.16 in its package.json, you should be fine. https://github.com/mjohnston/react-native-webpack-server/commit/d638bd42e7c89b79b1fd85172a859591363b6a67

**Comment by Harm-jeb** [comment]
I gathered the answer https://lnkr.fun/bf669ac
