### ISSUE TITLE
App crashes after touching Android annotation

### ISSUE THREAD

**Issue by AidenMontgomery** [nitaliano/react-native-mapbox-gl#233]
After adding an annotation to the map the application will consistently crash after tapping on one of the markers.

This may only be happening if the marker touched is removed from the map before the information popup is displayed.

``` bash
E/ViewRootImpl(11795): com.easybus/com.easybus.MainActivity : Only the original thread that created a view hierarchy can touch its views.
E/ViewRootImpl(11795): java.lang.RuntimeException
E/ViewRootImpl(11795):  at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:5333)
E/ViewRootImpl(11795):  at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1022)
E/ViewRootImpl(11795):  at android.view.View.requestLayout(View.java:15648)
E/ViewRootImpl(11795):  at android.view.View.requestLayout(View.java:15648)
E/ViewRootImpl(11795):  at android.view.View.requestLayout(View.java:15648)
E/ViewRootImpl(11795):  at android.view.View.requestLayout(View.java:15648)
E/ViewRootImpl(11795):  at android.view.View.requestLayout(View.java:15648)
E/ViewRootImpl(11795):  at android.view.ViewGroup.removeView(ViewGroup.java:3550)
E/ViewRootImpl(11795):  at com.mapbox.mapboxsdk.annotations.InfoWindow.close(InfoWindow.java:174)
E/ViewRootImpl(11795):  at com.mapbox.mapboxsdk.annotations.Marker.hideInfoWindow(Marker.java:44)
E/ViewRootImpl(11795):  at com.mapbox.mapboxsdk.views.MapView.removeAllAnnotations(MapView.java:2074)
E/ViewRootImpl(11795):  at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLManager.removeAllAnnotations(ReactNativeMapboxGLManager.java:322)
E/ViewRootImpl(11795):  at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule.removeAllAnnotations(ReactNativeMapboxGLModule.java:101)
E/ViewRootImpl(11795):  at java.lang.reflect.Method.invokeNative(Native Method)
E/ViewRootImpl(11795):  at java.lang.reflect.Method.invoke(Method.java:511)
E/ViewRootImpl(11795):  at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:249)
E/ViewRootImpl(11795):  at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:158)
E/ViewRootImpl(11795):  at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:58)
E/ViewRootImpl(11795):  at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:427)
E/ViewRootImpl(11795):  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/ViewRootImpl(11795):  at android.os.Handler.handleCallback(Handler.java:725)
E/ViewRootImpl(11795):  at android.os.Handler.dispatchMessage(Handler.java:92)
E/ViewRootImpl(11795):  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/ViewRootImpl(11795):  at android.os.Looper.loop(Looper.java:158)
E/ViewRootImpl(11795):  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137)
E/ViewRootImpl(11795):  at java.lang.Thread.run(Thread.java:864)
W/dalvikvm(11795): threadid=12: thread exiting with uncaught exception (group=0x4106da08)
E/AndroidRuntime(11795): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime(11795): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime(11795):    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:5335)
E/AndroidRuntime(11795):    at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1022)
E/AndroidRuntime(11795):    at android.view.View.requestLayout(View.java:15648)
E/AndroidRuntime(11795):    at android.view.View.requestLayout(View.java:15648)
E/AndroidRuntime(11795):    at android.view.View.requestLayout(View.java:15648)
E/AndroidRuntime(11795):    at android.view.View.requestLayout(View.java:15648)
E/AndroidRuntime(11795):    at android.view.View.requestLayout(View.java:15648)
E/AndroidRuntime(11795):    at android.view.ViewGroup.removeView(ViewGroup.java:3550)
E/AndroidRuntime(11795):    at com.mapbox.mapboxsdk.annotations.InfoWindow.close(InfoWindow.java:174)
E/AndroidRuntime(11795):    at com.mapbox.mapboxsdk.annotations.Marker.hideInfoWindow(Marker.java:44)
E/AndroidRuntime(11795):    at com.mapbox.mapboxsdk.views.MapView.removeAllAnnotations(MapView.java:2074)
E/AndroidRuntime(11795):    at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLManager.removeAllAnnotations(ReactNativeMapboxGLManager.java:322)
E/AndroidRuntime(11795):    at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule.removeAllAnnotations(ReactNativeMapboxGLModule.java:101)
E/AndroidRuntime(11795):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(11795):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(11795):    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:249)
E/AndroidRuntime(11795):    at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:158)
E/AndroidRuntime(11795):    at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:58)
E/AndroidRuntime(11795):    at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:427)
E/AndroidRuntime(11795):    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/AndroidRuntime(11795):    at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(11795):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(11795):    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime(11795):    at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime(11795):    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137)
E/AndroidRuntime(11795):    at java.lang.Thread.run(Thread.java:864)
```

**Comment by bsudekum** [comment]
Closing in favor of https://github.com/mapbox/react-native-mapbox-gl/issues/234

**Comment by AidenMontgomery** [comment]
I believe that this was crashing for me even without custom annotation images, which was the focus of #234
