### ISSUE TITLE
Android: Crash on tablet running android 4.4.4

### ISSUE THREAD

**Issue by jabm111** [nitaliano/react-native-mapbox-gl#267]
I don't know how useful this is and I'm not really sure what else I can do to debug, but when I run on a genymotion tablet running android 4.4.4 (API 19 2560x1600) it crashes with: 'Unfortunately, maptest has stopped'.

Android index file:
https://gist.github.com/jabm111/d54b01bdce8e4df40405
Package.json:
https://gist.github.com/jabm111/05b25463f30c0e5f7997

Didn't see anything interesting from adb logcat *:S ReactNative:V ReactNativeJS:V
`I/ReactNativeJS( 2093): Running application "maptest" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF`

The code works on a genymotion Nexus 5 running android 6.0.0 and an iPhones 5s simulator. Let me know if I can provide any more information. What is the minimum android version supported?

**Comment by jabm111** [comment]
I tried this again and was able to reproduce on a genymotion Samsung Galaxy S4 running Android 4.4.4 as well (API 19).

Here is the stacktrace from the genymotion tablet running 4.4.4:

https://gist.github.com/jabm111/887501189dbd7126fa80

Thanks!

**Comment by jabm111** [comment]
Hey, have you had a chance to take a look at this? Do you think this is related to one of these:

https://github.com/mapbox/mapbox-gl-native/issues/3247

https://github.com/mapbox/mapbox-gl-native/issues/2995

Any idea when v4.0.0 of mapbox-gl-native is scheduled for release?
Thanks

**Comment by vfaSonnt** [comment]
I don't know why but mapbox can not run on Genymotion with SDK version under 5.0. Above OS 5.0, it work well.
But I try on real device OS 4.4.x , it is OK.

**Comment by dapetcu21** [comment]
Does this still happen since? We're now on mapbox-gl-native 4.1.1.

**Comment by jemshit** [comment]
Works on real 4.4.4, not on genymotion 4.4.4, 4.2.2. Using lib v 4.2.0-snapshot
Error:
```
FATAL EXCEPTION: main
                                                                         Process: com.xx.myapp.debug, PID: 1591
                                                                         java.lang.Error: eglChooseConfig() failed
                                                                             at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
                                                                             at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:115)
                                                                             at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:468)
                                                                             at com.pordiva.skylife.manager.MapboxManager.onCreate(MapboxManager.java:843)
                                                                             at com.xx.myapp.ui.destination_detail.harita.DestinationMapActivity.onCreate(DestinationMapActivity.java:228)
                                                                             at android.app.Activity.performCreate(Activity.java:5231)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                             at dalvik.system.NativeStart.main(Native Method)
```
