### ISSUE TITLE
Staging Credentials

### ISSUE THREAD

**Issue by ouya99** [nitaliano/react-native-mapbox-gl#399]
Hi,

I managed to build the app including TelemetryService (one line in Manifest) on Android.

Now I have a crash (NPE?) accessing some telemetry credentials from an Android bundle? 

Any idea what this is?

`E/MapboxEventManager(19672): Error Trying to load Staging Credentials: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
`

complete stack trace (launch on android device)

```
08-07 11:01:53.924: E/ANDR-PERF-LOCK(2098): Failed to reset optimization for resource: 4 level: 0
08-07 11:01:53.986: E/native(777): do suspend false
08-07 11:01:55.087: E/BrcmNfcJni(1494): nfaConnectionCallback: unknown event ????
08-07 11:01:57.116: E/WifiConfigStore(777): saveWifiConfigBSSID Setting BSSID for "SEMINARISTEN"WPA_PSK to any
08-07 11:01:57.857: E/Finsky(19421): [1] com.google.android.finsky.wear.bo.a(837): onConnectionFailed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
08-07 11:02:05.339: E/WifiConfigStore(777): SSID temp disabled for  "SEMINARISTEN"WPA_PSK had autoJoinStatus=0 self added false ephemeral false
08-07 11:02:05.339: E/WifiConfigStore(777):  message=id=62 ssid="SEMINARISTEN" auth_failures=1 duration=10 reason=WRONG_KEY
08-07 11:02:06.108: E/installd(200): Couldn't opendir /data/app/vmdl1280295909.tmp: No such file or directory
08-07 11:02:07.159: E/NetworkScheduler.SR(1191): Invalid parameter app
08-07 11:02:07.159: E/NetworkScheduler.SR(1191): Invalid package name : Perhaps you didn't include a PendingIntent in the extras?
08-07 11:02:07.177: E/Drive.UninstallOperation(2378): Package still installed com.rnapp
08-07 11:02:07.384: E/Quickoffice(19609): An exception occured in getAllMountedStorages method.
08-07 11:02:07.384: E/Quickoffice(19609): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.qo.android.filesystem.h.a(com.qo.android.filesystem.StorageDefinition)' on a null object reference
08-07 11:02:07.384: E/Quickoffice(19609):   at com.quickoffice.mx.engine.a.e(AndroidLocalFileSystems.java:432)
08-07 11:02:07.384: E/Quickoffice(19609):   at com.quickoffice.mx.engine.a.a(AndroidLocalFileSystems.java:92)
08-07 11:02:07.384: E/Quickoffice(19609):   at com.quickoffice.mx.S.b(MxPlugin.java:59)
08-07 11:02:07.384: E/Quickoffice(19609):   at com.quickoffice.mx.engine.q.f(MxEngine.java:1225)
08-07 11:02:07.384: E/Quickoffice(19609):   at com.quickoffice.mx.engine.q.a(MxEngine.java:1219)
08-07 11:02:07.384: E/Quickoffice(19609):   at com.qo.android.b.call(AsyncTask.java:217)
08-07 11:02:07.384: E/Quickoffice(19609):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-07 11:02:07.384: E/Quickoffice(19609):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-07 11:02:07.384: E/Quickoffice(19609):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-07 11:02:07.384: E/Quickoffice(19609):   at java.lang.Thread.run(Thread.java:818)
08-07 11:02:07.436: E/IntentOperationSvc(2378): Failed to instantiate Chimera operation impl, dropping operation
08-07 11:02:07.521: E/NetworkScheduler.SR(1191): Invalid parameter app
08-07 11:02:07.521: E/NetworkScheduler.SR(1191): Invalid package name : Perhaps you didn't include a PendingIntent in the extras?
08-07 11:02:07.530: E/Finsky(19421): [1] com.google.android.finsky.wear.bo.a(837): onConnectionFailed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
08-07 11:02:10.161: E/MapboxEventManager(19672): Error Trying to load Staging Credentials: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
08-07 11:02:12.148: E/WifiConfigStore(777): saveWifiConfigBSSID Setting BSSID for "SEMINARISTEN"WPA_PSK to any
08-07 11:02:12.292: E/WifiConfigStore(777): Ignoring SSID re-enabled from supplicant:  "SEMINARISTEN"WPA_PSK had autoJoinStatus=0 self added false ephemeral false
08-07 11:02:15.308: E/GMPM(19878): GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
08-07 11:02:15.308: E/GMPM(19878): Scheduler not set. Not logging error/warn.
08-07 11:02:15.323: E/GMPM(19878): Uploading is not possible. App measurement disabled
08-07 11:02:15.692: E/NetworkScheduler(1191): com.tinder requested task be persisted for tag: 'global-ping' but does not hold the permission android.Manifest.permission.RECEIVE_BOOT_COMPLETED. This task won't be persisted.
```

**Comment by ouya99** [comment]
not valid anymore

**Comment by henrikra** [comment]
@java99 How did you solve this? I got similar error:
`07-26 16:02:47.050 11377-11377/com.myApp E/MapboxEventManager: Error Trying to load Staging Credentials: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.BaseBundle.getString(java.lang.String)' on a null object reference`

**Comment by henrikra** [comment]
Ah lol :') The problem was that the phone did not have internet connection :D Now I can see the map!
