### ISSUE TITLE
Cannot build unless enable multidex

### ISSUE THREAD

**Issue by pewh** [nitaliano/react-native-mapbox-gl#479]
I get this error when build android.

```
Dex: The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
        at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
        at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
        at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
...
```

After I read the docs, it suggests me to enable multidex. Is there any side-effect if I enable multidex?

**NOTE:**
android/build.gradle file:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        // classpath 'com.google.gms:google-services:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.fabric.io/public' }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

android/app/build.gradle file:
```
...
dependencies {
    compile project(':react-native-mapbox-gl')
    compile project(':react-native-fabric-digits')
    compile project(':react-native-config')
    compile project(':react-native-mauron85-background-geolocation')
    compile project(':react-native-vector-icons')
    compile project(':react-native-share')
    compile project(':react-native-push-notification')
    compile project(':react-native-orientation')
    compile project(':react-native-image-picker')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-device-info')
    compile project(':react-native-snackbar')
    compile project(':react-native-android-wifi')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'  // From node_modules
    compile 'com.google.android.gms:play-services-gcm:9.2.1'
}
...
```

**Comment by pewh** [comment]
It successes to build when I enable multidex. Unfortunately, it crashes to run because `react-native-config` (plugin I used) seems not support multidex.

**Comment by Gp2mv3** [comment]
Hey, how did you enabled MultiDex ?
When following the official doc, I have an infinite compilation until Java says that there is no more Heap space (after 15 minutes).
