### ISSUE TITLE
Importing Mapbox, { MapView } causes error

### ISSUE THREAD

**Issue by jaapster** [nitaliano/react-native-mapbox-gl#566]
Just adding the following line to my app triggers an error:

`import Mapbox, { MapView } from 'react-native-mapbox-gl';`

![screen shot 2017-05-31 at 10 23 54](https://cloud.githubusercontent.com/assets/1597572/26622713/9166ebe8-45eb-11e7-9f7a-46b97f0f30f1.png)

I'm getting this stack trace
`TypeError: Cannot match against 'undefined' or 'null'.
    at launchEditor (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/react-native/local-cli/server/util/launchEditor.js:154:27)
    at Object.handle (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/react-native/local-cli/server/middleware/openStackFrameInEditorMiddleware.js:17:7)
    at next (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/connect/lib/proto.js:174:15)
    at Object.compression [as handle] (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/compression/index.js:205:5)
    at next (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/connect/lib/proto.js:174:15)
    at IncomingMessage.<anonymous> (/Users/jaaplous/WebstormProjects/seLiteNative/node_modules/react-native/local-cli/server/middleware/loadRawBodyMiddleware.js:20:5)`

What am I doing wrong?

**Comment by frankbolviken** [comment]
Having the same issue.

**Comment by ghost** [comment]
Same here, I followed the iOS installation instructions perfectly. Still thinks MapView properties are undefined no matter what.

**Comment by HuiguangChu** [comment]
Having the same issue

**Comment by slushnys** [comment]
Any updates on this?

**Comment by henrikra** [comment]
You guys haven't installed native side of this library correctly. Have you guys figured it out?
