### ISSUE TITLE
Crashing on 5.2.3-alpha1

### ISSUE THREAD

**Issue by lucasbento** [nitaliano/react-native-mapbox-gl#655]
Version `5.2.3-alpha1` is crashing a lot here.

Sometimes it crashes a few seconds after I call any offline function, other times without doing anything and definitely crashes when I open a screen with a `<MapView />`.

This is the only thing that shows up on my debug:

```
2017-10-01 10:35:22.350 MyApp[60568:4704536] [INFO] {DefaultFileSource}[Database]: cannot open file at line 38280 of [0e5ffd9123] (Code 14)
2017-10-01 10:35:22.351 MyApp[60568:4704536] [INFO] {DefaultFileSource}[Database]: [0e5ffd9123]:38280: (3) open(/Users/user/Library/Developer/CoreSimulator/Devices/0CD9040D-A6B4-48A6-A646-5ABD8EFA4818/data/Containers/Data/Application/1D95FF0A-6779-45D9-8687-11D85C11B43C/Library/Application Support/com.MyApp/.mapbox/cache.db) -  (Code 14)
2017-10-01 10:35:22.364 [info][tid:com.facebook.react.JavaScript] Running application "MyApp" with appParams: {"rootTag":1,"initialProps":{"iOSDevice":"x86_64"}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
MyApp(60568,0x70000a27c000) malloc: *** error for object 0x10fae9a78: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

cc @nitaliano.

**Comment by dviluk** [comment]
Same for me on Android

```
 I/ReactNativeJS: Running application "map.index" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID7","navigatorID":"navigatorID1_nav0","navigatorEventID":"screenInstanceID7_events"},"rootTag":31}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
D/dalvikvm: GC_CONCURRENT freed 230K, 9% free 12763K/14023K, paused 1ms+1ms, total 22ms
D/dalvikvm: GC_CONCURRENT freed 137K, 6% free 13301K/14023K, paused 12ms+3ms, total 30ms
D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 11ms
E/mbgl: {com.duni}[OpenGL]: eglChooseConfig() returned no configs.
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa62e3288)
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.Error: eglChooseConfig() failed
                      at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
                      at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:127)
                      at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:213)
                      at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLView.setupMapView(ReactNativeMapboxGLView.java:151)
                      at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLView.onAfterUpdateTransaction(ReactNativeMapboxGLView.java:105)
                      at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLManager.onAfterUpdateTransaction(ReactNativeMapboxGLManager.java:81)
                      at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLManager.onAfterUpdateTransaction(ReactNativeMapboxGLManager.java:37)
                      at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
                      at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:227)
                      at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:150)
                      at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:923)
                      at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:895)
                      at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                      at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                      at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:723)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                      at android.view.Choreographer.doFrame(Choreographer.java:524)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                      at android.os.Handler.handleCallback(Handler.java:615)
                      at android.os.Handler.dispatchMessage(Handler.java:92)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4745)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                      at dalvik.system.NativeStart.main(Native Method)
D/dalvikvm: GC_CONCURRENT freed 340K, 4% free 13745K/14215K, paused 13ms+13ms, total 38ms
I/Process: Sending signal. PID: 1292 SIG: 9
Application terminated.
```

**Comment by dviluk** [comment]
Updated:
I just downloaded the new version of genymotion and added Android 6.0.0 and works fine, and in my phones too (android 6.0.1 and 5.0.2)
Still not working on Android emulator 4.1.1 and 4.2.2 same error [#issuecomment-333920515](https://github.com/mapbox/react-native-mapbox-gl/issues/655#issuecomment-333920515)
___
same for `5.2.0`, maybe is react-native (0.48.3) o my emulator
package.json
```
{
  "name": "duni",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "android-release": "cd android && gradlew assembleRelease",
    "clean-android": "del android/build && del android/app/build"
  },
  "dependencies": {
    "@shoutem/theme": "^0.10.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.3",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-mapbox-gl": "5.2.0",
    "react-native-material-textfield": "^0.10.0",
    "react-native-navigation": "^1.1.228",
    "react-native-parallax-scroll-view": "^0.19.0",
    "react-native-pdf": "^1.3.3",
    "react-native-platform-touchable": "^1.1.1",
    "react-native-progress-bar-classic": "^1.2.1",
    "react-native-scrollable-tab-view": "^0.6.7",
    "react-native-vector-icons": "^4.4.0",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-persist": "^4.10.0",
    "redux-thunk": "^2.2.0",
    "throttle-debounce": "^1.0.1"
  },
  "devDependencies": {
    "babel-eslint": "^8.0.1",
    "babel-jest": "21.0.2",
    "babel-preset-react-native": "4.0.0",
    "eslint": "^4.8.0",
    "eslint-plugin-react": "^7.4.0",
    "jest": "21.1.0",
    "react-test-renderer": "16.0.0-alpha.12",
    "redux-logger": "^3.0.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Genymotion:
```
Android 5.0.0
Android 4.1.1
```

**Comment by dviluk** [comment]
i just found this [[android] native error when mapview.onCreate](https://github.com/mapbox/mapbox-gl-native/issues/9120), looks like it does not work for android 4.x

**Comment by lucasbento** [comment]
@nitaliano: can you please give some light on this?

Is the version `6` more stable to use?

**Comment by nitaliano** [comment]
There is a bug in the native SDK that is causing crashes for android 4.x.x. Outside of that for react-native-mapbox-gl 5.x.x I've seen a few issues related to the offline module causing crashes.

Version 6 is in good shape, it doesn't have offline support yet. But it will land within the next two weeks.  I would say hold off on using it in a production environment until we release the beta in two weeks. We're pushing to get version 6 into master in 3-4 weeks.

**Comment by lucasbento** [comment]
@nitaliano: I see, do you have any idea what's causing the problem I mentioned? It was in iOS `10.x`.

Thank you for replying, by the way.

**Comment by nitaliano** [comment]
@lucasbento Are you calling `await Mapbox.initializeOfflinePacks()` before any other offline API calls?

**Comment by calintamas** [comment]
@lucasbento were you able to resolve the issue? My app crashes at launch (5.2.3-alpha1, Android 7.0).

**Comment by lucasbento** [comment]
@calintamas: sorry, no. :/

Just upgraded to `6.x`.

**Comment by calintamas** [comment]
The issue was a conflict related to OkHttp package version. A solution is to add this 

```
configurations.all {
    resolutionStrategy {
        // force certain versions of dependencies (including transitive)
        force 'com.squareup.okhttp3:okhttp:3.4.1'
    }
}
```
in ` src/app/build.gradle`
