### ISSUE TITLE
eglChooseConfig() Error only with Genymotion (Android 4.x) 6.0.0-alpha2 and 5.2.0

### ISSUE THREAD

**Issue by dviluk** [nitaliano/react-native-mapbox-gl#657]
I just downloaded an emulator from Android Studio, and the error does not appear when MapView is called. This happen only in Genymotion (Android 4.x).
Not tested in a real device.
Update: Working on device with Android 4.4

Tested with `react-native-mapbox-gl@5.2.0` and `@mapbox/react-native-mapbox-gl@6.0.0-alpha2`

Code
```javascript

import Mapbox from '@mapbox/react-native-mapbox-gl';
const accessToken = 'token';
Mapbox.setAccessToken(accessToken);

class TestMapActivity extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Mapbox.MapView
                    style={{ flex: 1 }}
                    initialZoomLevel={1}
                />
            </View>
        );
    }
}
```
Package.json
```javascript
{
	"name": "map6",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"@mapbox/react-native-mapbox-gl": "6.0.0-alpha2",
		"react": "16.0.0-beta.5",
		"react-native": "0.49.1"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0-beta.5"
	},
	"jest": {
		"preset": "react-native"
	}
}

```
Android Studio (Emulator) Working!
```
Android 4.1.2 + Google APIS
```

Genymotion (Emulator)
```
Android 4.1.1
```
Error Log:
```
10-04 22:28:42.044 1131-1131/com.map6 E/mbgl: {com.map6}[OpenGL]: eglChooseConfig() returned no configs.
10-04 22:28:42.048 1131-1131/com.map6 D/AndroidRuntime: Shutting down VM
10-04 22:28:42.052 1131-1131/com.map6 W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa6240288)
10-04 22:28:42.056 1131-1131/com.map6 E/AndroidRuntime: FATAL EXCEPTION: main
                                                        java.lang.Error: eglChooseConfig() failed
                                                            at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
                                                            at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:130)
                                                            at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:199)
                                                            at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:194)
                                                            at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.<init>(RCTMGLMapView.java:107)
                                                            at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.createViewInstance(RCTMGLMapViewManager.java:73)
                                                            at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.createViewInstance(RCTMGLMapViewManager.java:29)
                                                            at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
                                                            at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
                                                            at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
                                                            at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006)
                                                            at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977)
                                                            at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                            at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                            at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:723)
                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                            at android.view.Choreographer.doFrame(Choreographer.java:524)
                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                            at android.os.Handler.handleCallback(Handler.java:615)
                                                            at android.os.Handler.dispatchMessage(Handler.java:92)
                                                            at android.os.Looper.loop(Looper.java:137)
                                                            at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                            at java.lang.reflect.Method.invoke(Method.java:511)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                            at dalvik.system.NativeStart.main(Native Method)
10-04 22:28:42.060 389-399/system_process W/ActivityManager:   Force finishing activity com.map6/.MainActivity

```

**Comment by nitaliano** [comment]
@dviluk Would you mind filing this under the mapbox-gl-native repo if this is still an issue for you?
