### ISSUE TITLE
Android crashes when trying to use SymbolLayer

### ISSUE THREAD

**Issue by sironjuh** [nitaliano/react-native-mapbox-gl#821]
I have an issue on Android with the SymbolLayer. Trying to use images I get a crash:

```
com.facebook.react.bridge.NoSuchKeyException: couldn't find key value in dynamic object
        at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
        at com.mapbox.rctmgl.components.styles.RCTMGLStyleValue.getString(RCTMGLStyleValue.java:52)
        at com.mapbox.rctmgl.components.styles.RCTMGLStyleFactory.setSymbolLayerStyle(RCTMGLStyleFactory.java:207)
        at com.mapbox.rctmgl.components.styles.layers.RCTMGLSymbolLayer.addStyles(RCTMGLSymbolLayer.java:55)
        at com.mapbox.rctmgl.components.styles.layers.RCTLayer.addToMap(RCTLayer.java:231)
        at com.mapbox.rctmgl.components.styles.layers.RCTMGLSymbolLayer.addToMap(RCTMGLSymbolLayer.java:34)
        at com.mapbox.rctmgl.components.styles.sources.RCTSource.addLayerToMap(RCTSource.java:108)
        at com.mapbox.rctmgl.components.styles.sources.RCTSource.addToMap(RCTSource.java:66)
        at com.mapbox.rctmgl.components.styles.sources.RCTMGLShapeSource.access$001(RCTMGLShapeSource.java:25)
        at com.mapbox.rctmgl.components.styles.sources.RCTMGLShapeSource$1.onAllImagesLoaded(RCTMGLShapeSource.java:66)
        at com.mapbox.rctmgl.utils.DownloadMapImageTask.onPostExecute(DownloadMapImageTask.java:65)
        at com.mapbox.rctmgl.utils.DownloadMapImageTask.onPostExecute(DownloadMapImageTask.java:22)
```
I'm passing the select icon like this:

```
const fillStyle = MapboxGL.StyleSheet.create({
    marker: {
        iconImage: MapboxGL.StyleSheet.identity('marker'),
        iconAllowOverlap: true,
        iconSize: MapboxGL.StyleSheet.identity('scale'),
        iconOffset: MapboxGL.StyleSheet.identity('offset'),
        textField: MapboxGL.StyleSheet.identity('name'),
    },
});
```
And the layer is initialized:

```
        <MapboxGL.ShapeSource
            id={shapeId}
            images={{
                markerA,
                markerB,
            }}
            shape={routeShape}
        >
            <MapboxGL.SymbolLayer id={fillId} sourceID={shapeId} style={fillStyle.marker} />
        </MapboxGL.ShapeSource>
```
This works fine on an iOS.

React Native v0.50.4
react-native-mapbox-gl v6.0.0

Any pointers where to look at?

**Comment by nitaliano** [comment]
@sironjuh I'm assuming your features in your ShapeSource have a `marker` property? You can just do

```
iconImage: '{marker}'
```

I would recommend using token strings for iconImages

**Comment by sironjuh** [comment]
@nitaliano Excellent, switching from identity to plain '{marker}' fixed the Android crash. Since it was working on iOS I was a bit baffled what was causing it, as all the other values got through just fine.

Thanks!
