### ISSUE TITLE
[v6] Crash on exit

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#822]
Editing the app caused a crash.  This was collected by google play.

java.lang.RuntimeException: Unable to destroy activity {com.snow_trails/com.snow_trails.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.terminateContext()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4639)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4662)
	at android.app.ActivityThread.-wrap7(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.terminateContext()' on a null object reference
	at com.mapbox.mapboxsdk.maps.MapView.onDestroy(MapView.java:264)
	at com.mapbox.rctmgl.components.mapview.RCTMGLMapView$5.onHostDestroy(RCTMGLMapView.java:775)
	at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:231)
	at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState(ReactInstanceManager.java:641)
	at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:562)
	at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:576)
	at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:142)
	at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:72)
	at android.app.Activity.performDestroy(Activity.java:7165)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4626)

**Comment by nitaliano** [comment]
This is also posted here https://github.com/mapbox/react-native-mapbox-gl/issues/749 I'm going to close this out as a dup and we can track progress in 749. Thanks for posting!
