### ISSUE TITLE
[Android] Duplicate Entry: SafeIterableMap$Entry.class

### ISSUE THREAD

**Issue by luskin** [nitaliano/react-native-mapbox-gl#831]
Hello. As soon as I add the react-native-mapbox-gl package to android I begin to get the following error:

>Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/arch/core/internal/SafeIterableMap$Entry.class

My project build.gradle is as follows:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.1.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "$rootDir/../node_modules/react-native/android" }
        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }
    }
}
```

and my app dependencies are:

```
dependencies {
    compile project(':react-native-navigation')
    compile project(':react-native-intercom')
    compile project(':react-native-image-picker')
    compile project(':react-native-code-push')
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.1.0"
    compile "com.facebook.react:react-native:+"  // From node_modules

    // Firebase dependencies
    compile "com.google.firebase:firebase-core:11.6.0"
    compile "com.google.firebase:firebase-auth:11.6.0"
    compile "com.google.firebase:firebase-messaging:11.6.0"
    compile "com.google.firebase:firebase-database:11.6.0"

    // Intercom Dependencies
    compile 'io.intercom.android:intercom-sdk-base:4.+'
    compile 'io.intercom.android:intercom-sdk-fcm:4.+'

    // Geolocation
    compile project(':react-native-background-geolocation')
    compile(name: 'tslocationmanager', ext: 'aar')

    // Mapbox
    compile project(':mapbox-react-native-mapbox-gl')

    // Google Play Services
    compile ("com.google.android.gms:play-services-base:11.6.0") { force = true }
    compile ("com.google.android.gms:play-services-maps:11.6.0") { force = true }
}
```

I have multiDexEnabled true and I'm using 26 for sdk and build tools

The logcat is showing the following:

```
12-01 13:33:41.483 18123-18123/? E/SemAffinityControl: SemAffinityControl: registerfunction enter
12-01 13:33:41.489 18123-18123/? E/System: Unable to open boot classpath entry: /system/framework/oem-services.jar
12-01 13:33:41.490 18123-18123/? E/System: java.util.zip.ZipException: File too short to be a zip file: 0
                                               at java.util.zip.ZipFile.<init>(ZipFile.java:208)
                                               at java.util.zip.ZipFile.<init>(ZipFile.java:147)
                                               at java.util.jar.JarFile.<init>(JarFile.java:161)
                                               at java.util.jar.JarFile.<init>(JarFile.java:98)
                                               at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
                                               at java.lang.VMClassLoader.createBootClassPathUrlHandlers(VMClassLoader.java:49)
                                               at java.lang.VMClassLoader.<clinit>(VMClassLoader.java:31)
                                               at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                               at java.util.ResourceBundle$RBClassLoader.loadClass(ResourceBundle.java:452)
                                               at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2569)
                                               at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1438)
                                               at java.util.ResourceBundle.findBundle(ResourceBundle.java:1402)
                                               at java.util.ResourceBundle.findBundle(ResourceBundle.java:1356)
                                               at java.util.ResourceBundle.findBundle(ResourceBundle.java:1356)
                                               at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1298)
                                               at java.util.ResourceBundle.getBundle(ResourceBundle.java:723)
                                               at java.util.logging.Level.<init>(Level.java:223)
                                               at java.util.logging.Level.<clinit>(Level.java:96)
                                               at java.util.logging.Logger.<clinit>(Logger.java:177)
                                               at java.util.logging.Logger.getLogger(Logger.java:393)
                                               at android.icu.util.TimeZone.<clinit>(TimeZone.java:92)
                                               at java.util.TimeZone.setDefault(TimeZone.java:712)
                                               at com.android.internal.os.RuntimeInit.commonInit(RuntimeInit.java:177)
                                               at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
```

I've searched through similar issues posted but none of these have been able to solve my problem. I would really like to use Mapbox in our application if possible.

**Comment by nitaliano** [comment]
@luskin what that error is saying is `android/arch/core` is being brought in twice, so two of your deps are requiring this. You need to exclude it from one of your deps

Try
```
compile(project(':mapbox-react-native-mapbox-gl')){
  exclude group: 'android.arch.core'
}
```

**Comment by luskin** [comment]
Hi @nitaliano - you are a life saver thank you for the quick response. This solved my problem immediately.
