### ISSUE TITLE
Android crash when rendering annotation: A catalyst view must have an explicit width and height given to it.

### ISSUE THREAD

**Issue by JakielaAdam** [nitaliano/react-native-mapbox-gl#835]
I have existing code which works fine on iOS however, when I try and run it on Android, the app crashes. Specifically, I am having problems rendering annotations: Here is my code:

```
renderMapBoxMarkers() {
    var items = [];
    for(var i = 0; i < this.state.markers.length; i++) {
      var marker = this.state.markers[i];
      var key = marker.id + marker.stationId.toString();
      items.push(
        <MapboxGL.PointAnnotation
          key={key}
          id={key}
          title={key}
          selected={i === 0}
          coordinate={[marker.coordinates[1], marker.coordinates[0]]}>
          <View style={{width: 50, height: 50, backgroundColor: 'red'}}/>
        </MapboxGL.PointAnnotation>
      )
    }
    return items;
  }
```

Normally I will render an image for the marker, but for testing, just a simple view. When I run this, I get a native crash:

```
2-04 08:52:57.982 23521-23521/com.movatic.userapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.movatic.userapp, PID: 23521
                                                                     java.lang.IllegalStateException: A catalyst view must have an explicit width and height given to it. This should normally happen as part of the standard catalyst UI framework.
                                                                         at com.facebook.react.uimanager.MeasureSpecAssertions.assertExplicitMeasureSpec(MeasureSpecAssertions.java:24)
                                                                         at com.facebook.react.views.view.ReactViewGroup.onMeasure(ReactViewGroup.java:117)
                                                                         at android.view.View.measure(View.java:18586)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
                                                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
                                                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
                                                                         at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
                                                                         at android.view.View.measure(View.java:18586)
                                                                         at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                         at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                                         at android.view.View.measure(View.java:18586)
                                                                         at com.mapbox.mapboxsdk.annotations.MarkerViewManager.ensureInfoWindowOffset(MarkerViewManager.java:599)
                                                                         at com.mapbox.mapboxsdk.maps.AnnotationManager.selectMarker(AnnotationManager.java:346)
                                                                         at com.mapbox.mapboxsdk.maps.MapboxMap.selectMarker(MapboxMap.java:1500)
                                                                         at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.selectAnnotation(RCTMGLMapView.java:392)
                                                                         at com.mapbox.rctmgl.components.annotation.RCTMGLPointAnnotation$1.run(RCTMGLPointAnnotation.java:182)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:145)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5972)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

If I understand this properly, there is an error because the view I am trying to render does not have a width or height. However, I have assigned an explicit width and height to the view being rendered. Does anyone have any ideas on why this is not working?

**Comment by nitaliano** [comment]
Try adding a style with a width and height to your `PointAnnotation` component. Also have you looked into using a `ShapeSource` with a `SymbolLayer` like this [example](https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/CustomIcon.js)

**Comment by JakielaAdam** [comment]
Thank you for the suggestion. I have tried setting the dimentions of the PointAnnotation via props and styles with no luck.

Ex.
`style={{height: 50, width: 50}}
`
and 

```
height={50}
width={50
```

**Comment by JakielaAdam** [comment]
Ended up getting it working with the styles. Thank you for your help.

**Comment by nitaliano** [comment]
@JakielaAdam would you mind posting what you ended up doing just incase anyone else is running into this issue?

**Comment by Aaron-xyd** [comment]
@JakielaAdam I have also encountered this problem. May I ask what was the final solution? Thank you.
