### ISSUE TITLE
Getting IncompatibleClassChangeError with 6.0.2. 

### ISSUE THREAD

**Issue by joshuapinter** [nitaliano/react-native-mapbox-gl#943]
```java
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.insightemissions.trak.debug, PID: 4780
java.lang.IncompatibleClassChangeError: The method 'boolean com.google.android.gms.common.api.GoogleApiClient.isConnected()' was expected to be of type virtual but instead was found to be of type interface (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
    at com.mapbox.services.android.telemetry.location.GoogleLocationEngine.connect(GoogleLocationEngine.java:144)
    at com.mapbox.services.android.telemetry.location.GoogleLocationEngine.activate(GoogleLocationEngine.java:51)
    at com.mapbox.services.android.telemetry.MapboxTelemetry.registerLocationUpdates(MapboxTelemetry.java:487)
    at com.mapbox.services.android.telemetry.MapboxTelemetry.setTelemetryEnabled(MapboxTelemetry.java:427)
    at com.mapbox.services.android.telemetry.MapboxTelemetry.loadUserPreferences(MapboxTelemetry.java:397)
    at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:178)
    at com.mapbox.services.android.telemetry.MapboxTelemetry.initialize(MapboxTelemetry.java:125)
    at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
    at com.mapbox.rctmgl.modules.RCTMGLModule$1.run(RCTMGLModule.java:268)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by joshuapinter** [comment]
Okay, this was due to an old version dependency of Google Play Services: 

`compile 'com.google.android.gms:play-services:6.5.87'`

Plus, it's not good practice to include the entire library, so I updated this to: 

`compile 'com.google.android.gms:play-services-location:11.8.0'`

And this error went away.
