### ISSUE TITLE
(Android only) App freezes if you destroy activity and re-enter Application

### ISSUE THREAD

**Issue by cpetzel** [nitaliano/react-native-mapbox-gl#999]
This issue is reproducible in the Example app in this repo. 

Steps to reproduce. 
1.) Run the example app
2.) Select the "Show Map" option and grant the location permission. 
3.) Observe that the app is requesting location in the status bar and displaying your location on the map. 
4.) Press back to dismiss the modal/map. (Observe that the application is still listening for location updates (status bar) even though the MapView is no longer visible)
5.) Press back again to destroy the activity. (Observe that the application is still listening for location updates (indicator in status bar)
6.) Relaunch the app (Observe a white screen. Pressing back again crashes the process)

I have verified that the LocationManager is notified to dispose itself in the react lifecycle callback [onHostDestroy()](https://github.com/mapbox/react-native-mapbox-gl/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L1014) Which deactivates the locationEngine. But somehow the Lost engine process is still alive and still asking for updates. 

After relaunching the app, This is the stack trace...
Seems like an IPC issue? The :lost process not communicating correctly? 

``` E/FusedLocationProviderServiceDelegate: Error occurred trying to report a new Location
                                                                         android.os.DeadObjectException
                                                                             at android.os.BinderProxy.transactNative(Native Method)
                                                                             at android.os.BinderProxy.transact(Binder.java:764)
                                                                             at com.mapzen.android.lost.internal.IFusedLocationProviderCallback$Stub$Proxy.onLocationChanged(IFusedLocationProviderCallback.java:129)
                                                                             at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(FusedLocationProviderServiceDelegate.java:95)
                                                                             at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:191)
                                                                             at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:292)
                                                                             at android.location.LocationManager$ListenerTransport.-wrap0(Unknown Source:0)
                                                                             at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:244)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)```

**Comment by nitaliano** [comment]
@cpetzel thanks for reporting we have another issue open for this already here https://github.com/mapbox/react-native-mapbox-gl/issues/925 what you have reported is new information about being able to reproduce this issue. I'm going to close this issue out so we keep the conversation under one ticket.

**Comment by cpetzel** [comment]
thanks @nitaliano , We plan on forking the repo to fix this. 

We plan on creating new react methods to allow the JS code to tell the MapView where the user is. This way, we can disable the Lost Engine and use a location provider on the JS side (many options available on both platforms). We then can simply pass the JS location information into the MapboxView so it can re-render. (basically hook into [this](https://github.com/scootnetworks/react-native-mapbox-gl/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L135) callback with our own 'engine' on the JS side). This way, all of the followModes and mapbox user location stuff can stay the way it is.
